name: Meson CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip
          pip install meson

      - name: Setup GCC (Linux)
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13
          platform: x64

      - name: Configure
        run: meson setup build -Dbuildtype=release -Dtests=true

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build
